defaults:
  - _self_
  - dataset: office-31
  - method: ros
  # 必须开启这个 override 才能使用彩色控制台
  - override hydra/job_logging: colorlog

# 全局参数
batch_size: 32
num_workers: 4
device: cuda
seed: 42
exp_name: "test_run"

hydra:
  run:
    dir: ${hydra:runtime.cwd}/../results/${now:%Y-%m-%d}/${now:%H-%M-%S}_${exp_name}

  job:
    chdir: True
